name: Image database CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    uses: forcet/devop-template/.github/workflows/docker-image-devop-template.yml@main
    with:
      helm_name: helm-template
      helm_release: forcet-poke-mongo
      helm_version: 8
      namespace: forcet22-dev
    secrets: inherit